# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ayush Shahi
email: ayush.raj.shahi.ars@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am pursuing a Ph.D. in environmental engineering and a Graduate Certificate in Global Engineering. My research focuses on water treatment, arsenic treatment in drinking water using ion exchange, and nanofiltration. I have over five years of research experience and have been part of three research publications and have presented at six conferences. I have worked as a teaching assistant for two semesters and have been an invited speaker six times. In the past three years, I have been awarded an international scholarship, a national scholarship, four fellowships/endowments, and three presentation awards. My professional goals are to develop treatment systems for water access in water-stressed regions. I plan to work in research and development after I graduate. I expect to graduate in July 2023.
baseurl: "/pages-sample" # the subpath of your site, e.g. /blog
url: "https://arajshahi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

#header_pages:
#  - 01-about.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
